'use client';
/**
 * Purpose: Two-fingerprint side-by-side diff card. Renders:
 *          1. Two FingerprintBadge chips at the top (A → B).
 *          2. A delta list — one row per structural change with the
 *             narrative explanation generated by the backend.
 *          3. A bottom "why these diverge" hint for identical pairs.
 *
 *          This is the primary UI for THESIS-05 §4 ("Fingerprint
 *          Comparison / Trace Diff"). The line-by-line walkthrough that
 *          pins the structural change lives on the /tracer/compare page
 *          (it has access to the actual trace steps); this component
 *          is the field-level summary.
 *
 * Collaborators: types/fingerprint, hooks/useFingerprintDiff
 * Last significant change: T1-D (Trace Diff)
 */
import type { ReactNode } from 'react';
import { FingerprintBadge } from '@/components/tracer/FingerprintBadge';
import { complexityBucket } from '@/types/fingerprint';
import type {
  FingerprintDiffDelta,
  FingerprintDiffResponse,
  FingerprintPayload,
} from '@/types/fingerprint';

interface FingerprintDiffProps {
  diff: FingerprintDiffResponse;
}

function formatValue(v: number | string | string[]): string {
  if (Array.isArray(v)) return v.length ? v.join(', ') : '—';
  if (typeof v === 'number') {
    if (Number.isInteger(v)) return String(v);
    return `${v.toFixed(1)}`;
  }
  return v;
}

export function FingerprintDiff({ diff }: FingerprintDiffProps): ReactNode {
  const { a, b, deltas, summary, identical } = diff;
  return (
    <section aria-label="Fingerprint diff">
      <header
        style={{
          display: 'flex',
          gap: '1rem',
          alignItems: 'center',
          flexWrap: 'wrap',
        }}
      >
        <FingerprintBadge fingerprint={a} detailed />
        <span
          aria-hidden
          style={{ fontSize: '1.25rem', color: 'var(--text-muted, #64748b)' }}
        >
          →
        </span>
        <FingerprintBadge fingerprint={b} detailed />
      </header>

      <p
        style={{
          margin: '1rem 0 0.75rem',
          color: 'var(--text-muted, #475569)',
          fontSize: '0.9rem',
        }}
      >
        {summary}
      </p>

      {identical ? (
        <IdenticalBanner a={a} b={b} />
      ) : (
        <DeltaList deltas={deltas} />
      )}
    </section>
  );
}

function IdenticalBanner({
  a,
  b,
}: {
  a: FingerprintPayload;
  b: FingerprintPayload;
}): ReactNode {
  const bucket = complexityBucket(a.conceptual_complexity);
  return (
    <div
      style={{
        padding: '0.85rem 1rem',
        border: '1px solid var(--success, #047857)',
        background: 'var(--success-bg, #d4f4dd)',
        borderRadius: '8px',
        color: 'var(--text, #1a1a1a)',
      }}
    >
      <strong>{bucket === 'green' ? 'Same control-flow shape.' : 'Same fingerprint.'}</strong>{' '}
      Two traces that produce an identical fingerprint share the same branch /
      loop / recursion structure — even if their variable names differ. Trace A
      and Trace B are structurally equivalent; the differences must be in
      values, not in shape.
    </div>
  );
}

function DeltaList({ deltas }: { deltas: FingerprintDiffDelta[] }): ReactNode {
  return (
    <ul
      style={{
        listStyle: 'none',
        padding: 0,
        margin: '0.75rem 0 0',
        display: 'grid',
        gap: '0.5rem',
      }}
    >
      {deltas.map((d) => (
        <li
          key={d.field}
          style={{
            padding: '0.7rem 0.9rem',
            border: '1px solid var(--border, #e5e7eb)',
            borderLeft: `4px solid ${
              d.significant ? 'var(--warning, #b45309)' : 'var(--border, #cbd5e1)'
            }`,
            borderRadius: '6px',
            background: 'var(--card-bg, #fff)',
          }}
        >
          <div
            style={{
              display: 'flex',
              flexWrap: 'wrap',
              gap: '0.4rem 0.9rem',
              alignItems: 'baseline',
            }}
          >
            <strong style={{ fontSize: '0.95rem' }}>{d.label}</strong>
            <code
              style={{
                fontFamily:
                  'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
                fontSize: '0.85rem',
                color: 'var(--text-muted, #475569)',
              }}
            >
              {formatValue(d.a_value)} → {formatValue(d.b_value)}
            </code>
            {d.significant && (
              <span
                style={{
                  fontSize: '0.7rem',
                  textTransform: 'uppercase',
                  letterSpacing: '0.04em',
                  color: 'var(--warning, #b45309)',
                  marginLeft: 'auto',
                }}
              >
                significant
              </span>
            )}
          </div>
          <p
            style={{
              margin: '0.4rem 0 0',
              fontSize: '0.85rem',
              color: 'var(--text, #1a1a1a)',
              lineHeight: 1.45,
            }}
          >
            {d.narrative}
          </p>
        </li>
      ))}
    </ul>
  );
}