'use client';
/**
 * Purpose: Active-learning checkpoint prompt (branch / variable / exception prediction).
 *          T1-C (Adaptive Checkpoint Difficulty): when the backend reports
 *          the selected checkpoint mode (scaffolded / contrastive), we
 *          expose a "Show hint" affordance. The hint is generated by the
 *          mode-aware system prompt — scaffolded = inline cue,
 *          contrastive = counterfactual probe.
 * Collaborators: —
 * Last significant change: T1-C (Adaptive Difficulty)
 */


import { useState, useCallback } from 'react';
import type { TraceCheckpoint, TraceStep } from '@/types/trace';
import { authFetch } from '@/lib/api';
import { trackEvent, trackLoadEvent } from '@/lib/analytics';
import styles from './TutorChallenge.module.css';

interface TutorChallengeProps {
  checkpoint: TraceCheckpoint;
  code: string;
  steps: TraceStep[];
  traceId?: string | null;
  /**
   * T1-C: the SM-2 concept tag for the current checkpoint. Forwarded to
   * the diagnose endpoint so the selector can choose the mode. When
   * omitted, the backend falls back to direct mode.
   */
  conceptTag?: string | null;
  onSuccess: () => void;
}

interface DiagnoseResponse {
  tag: string;
  explanation: string;
  hint?: string | null;
  checkpoint_mode?: string;
  checkpoint_mode_rationale?: string;
}

const API_BASE = (process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000') + '/api';

export function TutorChallenge({
  checkpoint,
  code,
  steps,
  traceId,
  conceptTag,
  onSuccess,
}: TutorChallengeProps) {
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);
  const [isLoadingDiagnose, setIsLoadingDiagnose] = useState(false);
  const [diagnoseResult, setDiagnoseResult] = useState<DiagnoseResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  // T1-C: when the backend's first /diagnose call selects a non-direct
  // mode, we surface a "Show hint" button before submission. The hint
  // is fetched on-demand (a second /diagnose call) to keep the first
  // call cheap — that way the direct-mode path stays unaffected.
  const [hintRevealed, setHintRevealed] = useState(false);
  const [hintLoading, setHintLoading] = useState(false);
  const [hintText, setHintText] = useState<string | null>(null);
  const [selectedMode, setSelectedMode] = useState<string | null>(null);

  const handleSubmit = useCallback(async (option: string) => {
    if (isSubmitted) return;
    setSelectedOption(option);
    setIsSubmitted(true);

    const correct = option === checkpoint.correct_value;
    setIsCorrect(correct);

      // Fire-and-forget: emit a load-pause event for the cognitive-load
      // dashboard (T1-A). The page passes a constant `concept_tag` from
      // the surrounding trace, so we tag it accordingly. We never block
      // the UX on this — trackEvent is a no-throw fetch.
      trackEvent('tutor_checkpoint_submitted', {
        checkpoint_type: checkpoint.checkpoint_type,
        concept_tag: conceptTag ?? null,
        correct,
      });
      if (!correct && traceId) {
        // T1-A: explicit load-event for the cognitive-load dashboard
        // (consumed by `load_estimator._interaction_score`). The
        // generic event above is for product analytics; this one is
        // tagged as a *miss* explicitly so the dashboard can
        // distinguish a miss from other tutor telemetry.
        trackLoadEvent('tutor_checkpoint_miss', {
          trace_id: traceId,
          concept_tag: conceptTag ?? null,
        });
      }

    if (correct) {
      // Correct! The user continues.
      return;
    }

    // Incorrect: Call LLM to diagnose misconception
    setIsLoadingDiagnose(true);
    setError(null);
    try {
      const payload = {
        code,
        checkpoint_type: checkpoint.checkpoint_type,
        variable_name: checkpoint.variable_name,
        correct_value: checkpoint.correct_value,
        user_prediction: option,
        line_number: checkpoint.line_number,
        trace_id: traceId || null,
        steps: steps, // Pass current trace steps for auto-saving
        concept_tag: conceptTag ?? null,
        // Don't pin `checkpoint_mode` here — let the selector pick.
        override_mode: false,
      };

      const res = await authFetch(`${API_BASE}/llm/diagnose`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        throw new Error('Failed to fetch explanation from AI Tutor');
      }

      const data: DiagnoseResponse = await res.json();
      setDiagnoseResult(data);
      setSelectedMode(data.checkpoint_mode ?? null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to reach AI Tutor');
    } finally {
      setIsLoadingDiagnose(false);
    }
  }, [checkpoint, code, steps, traceId, conceptTag, isSubmitted]);

  // T1-C: fetch the hint on-demand. The backend re-runs the diagnose
  // path with override_mode=true and the selected mode locked, which
  // makes the system prompt emit the scaffolded/contrastive `hint`
  // field. We only call this when the first response selected a
  // non-direct mode (so direct-mode users never see the hint UI).
  const handleShowHint = useCallback(async () => {
    if (hintRevealed || !selectedMode || selectedMode === 'direct') return;
    setHintLoading(true);
    setError(null);
    try {
      const payload = {
        code,
        checkpoint_type: checkpoint.checkpoint_type,
        variable_name: checkpoint.variable_name,
        correct_value: checkpoint.correct_value,
        user_prediction: selectedOption ?? '',
        line_number: checkpoint.line_number,
        trace_id: traceId || null,
        steps,
        concept_tag: conceptTag ?? null,
        checkpoint_mode: selectedMode,
        override_mode: true,
      };
      const res = await authFetch(`${API_BASE}/llm/diagnose`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error('Failed to fetch hint');
      const data: DiagnoseResponse = await res.json();
      setHintText(data.hint ?? null);
      setHintRevealed(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to reach AI Tutor');
    } finally {
      setHintLoading(false);
    }
  }, [
    code,
    checkpoint,
    steps,
    traceId,
    conceptTag,
    selectedMode,
    selectedOption,
    hintRevealed,
  ]);

  const showHintButton =
    !isSubmitted &&
    (selectedMode === 'scaffolded' || selectedMode === 'contrastive') &&
    !hintRevealed;

  return (
    <div className={styles.container}>
      <div className={`${styles.card} ${isSubmitted ? (isCorrect ? styles.correctGlow : styles.incorrectGlow) : ''}`}>
        <div className={styles.header}>
          <span className={styles.badge}>◈ AI TUTOR CHALLENGE</span>
          <h3 className={styles.title}>Predict the Next State</h3>
          {selectedMode && selectedMode !== 'direct' && (
            <span
              className={styles.modeBadge}
              data-mode={selectedMode}
              title={
                selectedMode === 'scaffolded'
                  ? 'Scaffolded mode: a hint is available below.'
                  : 'Contrastive mode: a counterfactual probe is available below.'
              }
            >
              {selectedMode === 'scaffolded' ? '◇ scaffolded' : '◇ contrastive'}
            </span>
          )}
        </div>

        <p className={styles.prompt}>{checkpoint.prompt}</p>

        {/* T1-C: surface the hint when the mode adapter chose one. */}
        {showHintButton && (
          <div className={styles.hintBar}>
            <button
              type="button"
              className={styles.hintBtn}
              onClick={handleShowHint}
              disabled={hintLoading}
              aria-label="Show adaptive hint"
            >
              {hintLoading ? '◈ Loading hint…' : '◈ Show hint'}
            </button>
            <span className={styles.hintNote}>
              {selectedMode === 'scaffolded'
                ? 'You missed this concept recently — here is a targeted hint.'
                : 'You missed this concept twice — here is a counterfactual probe.'}
            </span>
          </div>
        )}

        {hintRevealed && hintText && (
          <div
            className={styles.hintCard}
            role="note"
            aria-label="Adaptive hint"
          >
            <span className={styles.hintLabel}>Hint</span>
            <p className={styles.hintText}>{hintText}</p>
          </div>
        )}

        {!isSubmitted ? (
          <div className={styles.optionsList}>
            {checkpoint.options.map((option, idx) => (
              <button
                key={idx}
                className={styles.optionBtn}
                onClick={() => handleSubmit(option)}
              >
                {option}
              </button>
            ))}
          </div>
        ) : (
          <div className={styles.resultSection}>
            {isCorrect ? (
              <div className={styles.successBox}>
                <span className={styles.statusIcon}>✓</span>
                <p className={styles.statusText}>Excellent! Your prediction is correct.</p>
                <button className={styles.actionBtn} onClick={onSuccess}>
                  Continue Trace
                </button>
              </div>
            ) : (
              <div className={styles.failureBox}>
                <span className={styles.statusIcon}>✕</span>
                <p className={styles.statusText}>
                  Your prediction was different: <code>{selectedOption}</code> (Expected: <code>{checkpoint.correct_value}</code>)
                </p>

                {isLoadingDiagnose && (
                  <div className={styles.diagnoseLoader}>
                    <span className={styles.spinner}>◈</span> Diagnosing misconception...
                  </div>
                )}

                {diagnoseResult && (
                  <div className={styles.feedbackCard}>
                    <span className={styles.misconceptionTag}>
                      Concept Gap: {diagnoseResult.tag.replace(/_/g, ' ')}
                    </span>
                    <p className={styles.explanationText}>
                      {diagnoseResult.explanation}
                    </p>
                  </div>
                )}

                {error && <p className={styles.errorText}>⚠ {error}</p>}

                <button className={styles.actionBtn} onClick={onSuccess} disabled={isLoadingDiagnose}>
                  Acknowledge & Continue
                </button>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
