-- ============================================================
-- V017: Adaptive checkpoint difficulty (THESIS-05 §3 — T1-C)
-- ============================================================
-- Today every Tutor Checkpoint is generated by the same prompt template
-- in `backend/app/services/llm_router.py`. This migration enables the
-- Adaptive Checkpoint Difficulty feature (T1-C): before generating the
-- next checkpoint, the system consults the student's recent SM-2
-- ratings on the current concept tag and selects one of three modes:
--
--   * direct       — the default, current behaviour
--   * scaffolded   — after 1 miss on the same concept in last 3 sessions
--   * contrastive  — after 2+ misses on the same concept
--
-- The selection is logged to `llm_call_metrics.checkpoint_mode` so the
-- A/B comparison can be sliced per-mode. The new column is nullable so
-- rows pre-dating this migration keep working without backfill.
--
-- Why a column on `llm_call_metrics` rather than a new table:
--   * The LLM-router call is the unit-of-work we want to slice on.
--     A separate `checkpoint_selections` table would require a join that
--     defeats the point of the metric.
--   * One row per checkpoint call keeps the schema flat for the existing
--     dashboards (§6 of docs/MEASUREMENT.md).
--
-- RLS: the column inherits the existing admin-only policy on
-- `llm_call_metrics`. End users don't read this directly; the dashboard
-- service-role SELECTs it through the same path the cache-hit rollup
-- uses.
-- ============================================================

ALTER TABLE llm_call_metrics
    ADD COLUMN IF NOT EXISTS checkpoint_mode TEXT
        CHECK (checkpoint_mode IN ('direct', 'scaffolded', 'contrastive'));

-- Most common query: "how many of each mode were selected last week?"
-- The index is conditional on `checkpoint_mode IS NOT NULL` so pre-V017
-- rows don't bloat it.
CREATE INDEX IF NOT EXISTS idx_llm_call_metrics_checkpoint_mode
    ON llm_call_metrics(checkpoint_mode)
    WHERE checkpoint_mode IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_llm_call_metrics_checkpoint_mode_created
    ON llm_call_metrics(checkpoint_mode, created_at DESC)
    WHERE checkpoint_mode IS NOT NULL;