"""Adaptive Checkpoint Difficulty — THESIS-05 §3 (T1-C).

Today every Tutor Checkpoint is generated by the same prompt template.
This module adds the *selection* logic that picks one of three modes
before each checkpoint call:

  * ``direct``       — the default, current behaviour
  * ``scaffolded``   — after 1 miss on the same concept in last 3 sessions
  * ``contrastive``  — after 2+ misses on the same concept

The selector is a *pure* function over (concept_tag, recent_events). It
does NOT talk to the LLM, the DB, or the cache. That separation matters:
we can unit-test the selection rubric without any infrastructure.

The system-prompt variant for each mode lives in
``app.services.llm_prompts`` (SYSTEM_MISCONCEPTION_*) so the router stays
focused on routing, not prompt engineering — see THESIS-05 §3
implementation sketch.
"""
from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from enum import Enum
from typing import Any


class CheckpointMode(str, Enum):
    """Three adaptation modes for the next Tutor Checkpoint."""

    DIRECT = "direct"
    SCAFFOLDED = "scaffolded"
    CONTRASTIVE = "contrastive"


@dataclass(frozen=True)
class CheckpointSelection:
    """Result of ``select_checkpoint_mode`` — the chosen mode + why.

    ``rationale`` is a short string the router logs alongside the
    ``llm_call_metrics.checkpoint_mode`` column so the methodology
    contribution can be sliced by *why* the system picked each mode.
    """

    mode: CheckpointMode
    rationale: str
    recent_miss_count: int
    recent_session_count: int


def _is_miss(rating: str | None) -> bool:
    """A miss on a concept is a review where the student answered 'again'
    (full reset under SM-2 — see ``frontend/lib/sm2.ts``). Anything else
    (hard, good, easy) counts as a non-miss.
    """
    return (rating or "").strip().lower() == "again"


def _distinct_session_count(
    events: Iterable[dict[str, Any]],
) -> int:
    """Number of distinct calendar days the student reviewed this concept.

    Sessions are session-bounded by date — we don't count two events on
    the same day as two sessions for the purpose of mode selection.
    """
    days: set[str] = set()
    for ev in events:
        # `occurred_at` is an ISO timestamp; slicing to the first 10
        # chars gives YYYY-MM-DD. If the field is missing we skip.
        occurred = ev.get("occurred_at")
        if not occurred:
            continue
        days.add(str(occurred)[:10])
    return len(days)


def select_checkpoint_mode(
    *,
    concept_tag: str | None,
    recent_review_events: Iterable[dict[str, Any]] | None = None,
    override_mode: CheckpointMode | str | None = None,
) -> CheckpointSelection:
    """Pick the adaptation mode for the next Tutor Checkpoint.

    Args:
        concept_tag: the SM-2 concept tag for the next checkpoint
            (e.g. ``loop_iteration_off_by_one``). When ``None`` the
            selector returns ``direct`` — there's no concept to adapt on.
        recent_review_events: optional iterable of dicts with at least
            ``concept_tag``, ``rating``, ``occurred_at``. Only events for
            the requested ``concept_tag`` are considered by the selector;
            pass the unfiltered stream and the selector will filter.
        override_mode: explicit override (e.g. from the A/B-test config).
            Bypasses the rubric — useful for "force contrastive" debug
            requests and for the methodology experiment arm that fixes
            the mode independent of recent misses.

    Returns:
        A ``CheckpointSelection`` whose ``mode`` is one of ``direct``,
        ``scaffolded``, or ``contrastive``. The ``rationale`` is the
        short string the router records in ``llm_call_metrics``.

    Selection rubric (THESIS-05 §3):
      * default → ``direct``
      * ≥ 1 miss on this concept in the last 3 sessions → ``scaffolded``
      * ≥ 2 misses on this concept in the last 3 sessions → ``contrastive``
    """
    if override_mode is not None:
        mode = (
            override_mode
            if isinstance(override_mode, CheckpointMode)
            else CheckpointMode(str(override_mode))
        )
        return CheckpointSelection(
            mode=mode,
            rationale=f"explicit_override:{mode.value}",
            recent_miss_count=-1,
            recent_session_count=-1,
        )

    if not concept_tag:
        return CheckpointSelection(
            mode=CheckpointMode.DIRECT,
            rationale="no_concept_tag",
            recent_miss_count=0,
            recent_session_count=0,
        )

    # Filter to this concept (defensive — callers sometimes pass everything).
    concept_events = [
        ev for ev in (recent_review_events or []) if ev.get("concept_tag") == concept_tag
    ]
    # Keep only the most recent 3 sessions (calendar days), which is the
    # THESIS-05 §3 rubric window.
    recent_days: list[str] = []
    seen_days: set[str] = set()
    for ev in sorted(
        concept_events, key=lambda e: str(e.get("occurred_at") or ""), reverse=True
    ):
        day = str(ev.get("occurred_at") or "")[:10]
        if not day:
            continue
        if day in seen_days:
            continue
        seen_days.add(day)
        recent_days.append(day)
        if len(recent_days) >= 3:
            break

    session_count = len(recent_days)
    miss_count = sum(
        1
        for ev in concept_events
        if str(ev.get("occurred_at") or "")[:10] in set(recent_days)
        and _is_miss(ev.get("rating"))
    )

    if session_count == 0:
        return CheckpointSelection(
            mode=CheckpointMode.DIRECT,
            rationale="no_recent_sessions",
            recent_miss_count=0,
            recent_session_count=0,
        )

    if miss_count >= 2:
        return CheckpointSelection(
            mode=CheckpointMode.CONTRASTIVE,
            rationale=(
                f"{miss_count}_misses_in_last_{session_count}_sessions"
            ),
            recent_miss_count=miss_count,
            recent_session_count=session_count,
        )
    if miss_count >= 1:
        return CheckpointSelection(
            mode=CheckpointMode.SCAFFOLDED,
            rationale=(
                f"{miss_count}_miss_in_last_{session_count}_sessions"
            ),
            recent_miss_count=miss_count,
            recent_session_count=session_count,
        )
    return CheckpointSelection(
        mode=CheckpointMode.DIRECT,
        rationale=f"no_misses_in_last_{session_count}_sessions",
        recent_miss_count=miss_count,
        recent_session_count=session_count,
    )


# Convenience: the THESIS-05 §3 wording for what each mode means. Kept
# here so the methodology contribution can quote it verbatim without
# reaching into the prompts module.
MODE_DESCRIPTIONS: dict[str, str] = {
    CheckpointMode.DIRECT.value: (
        "Direct mode (default). Predict-the-next-state prompt; same as the "
        "non-adaptive baseline."
    ),
    CheckpointMode.SCAFFOLDED.value: (
        "Scaffolded mode (after 1 miss on the same concept in the last 3 "
        "sessions). Adds an inline hint that draws the student's attention "
        "to the runtime feature that anchors the concept (e.g. update order, "
        "branch condition)."
    ),
    CheckpointMode.CONTRASTIVE.value: (
        "Contrastive mode (after 2+ misses on the same concept). Generates "
        "a counterfactual item: 'What if the loop were `for i in range(1, "
        "n)`? Would the answer change?' — the AIED-2025 EDGE pattern of a "
        "minimal perturbation that invalidates the shortcut."
    ),
}